### ISSUE TITLE
at some point will a version be created in ANDORID?

### ISSUE THREAD

**Issue by demur1** [PhoenixARC/-PCK-Studio#2]
I was wondering if at some point they are going to create an ANDORID version of the PCK STUDIO program?

**Comment by Korozin** [comment]
That really depends. Android can be tricky to develop especially if it's a C++ program. The easiest way to go if someone were to do this would in my eyes anyway be python but I highly doubt anyone is going to take the time to convert it like this. I already was involved in converting JGecko U to python and honestly I dont have the motivation atm to try doing it on a new program in a completely different language. So the answer is possibly, but not likely

**Comment by Korozin** [comment]
> That really depends. Android can be tricky to develop especially if it's a C++ program. The easiest way to go if someone were to do this would in my eyes anyway be python but I highly doubt anyone is going to take the time to convert it like this. I already was involved in converting JGecko U to python and honestly I dont have the motivation atm to try doing it on a new program in a completely different language. So the answer is possibly, but not likely

I mean C# not C++
