### ISSUE TITLE
Skin Not being found

### ISSUE THREAD

**Issue by samtallo1** [PhoenixARC/-PCK-Studio#22]
So I used Wii u PCK Installer so I can bring 2 skins to Minecraft wii u and after doing so I go back onto Minecraft and the solo I just replaced Says No Pack: Default Skins

**Comment by NessieHax** [comment]
The PCK Installer is no longer supported.
Please use a standalone FTP Client, such as [WinSCP](https://winscp.net/eng/download.php).
