### ISSUE TITLE
Remove slur from Pck Manager

### ISSUE THREAD

**Issue by bor-real** [PhoenixARC/-PCK-Studio#28]
![image](https://github.com/PhoenixARC/-PCK-Studio/assets/90580455/de84783f-35ed-4983-b7b9-577d95ac0d72)
The phrase on the right is a slur. Please change to JP.

**Comment by NessieHax** [comment]
I was not aware of that.
Changed in commit 1622ea72acb94d1783fb0e597e0ef3c453da897e
