### ISSUE TITLE
"+ Replace" Button Bug

### ISSUE THREAD

**Issue by AutoCarrot** [PhoenixARC/-PCK-Studio#33]
When adding a cape to a skin while creating a skin, a "+ Replace" button will appear at the very top left of the screen.

**Comment by bor-real** [comment]
![image](https://github.com/PhoenixARC/-PCK-Studio/assets/90580455/9975d47a-8998-48ae-8984-4956fb8a6443) Strange. For me its in the bottom right.

**Comment by AutoCarrot** [comment]
> ![image](https://github.com/PhoenixARC/-PCK-Studio/assets/90580455/9975d47a-8998-48ae-8984-4956fb8a6443) Strange. For me its in the bottom right.
> 

That's when pressing the skin's Show Replace button, I mean the cape' one.

**Comment by MattN-L** [comment]
This is... odd. Looking into it soon.

**Comment by NessieHax** [comment]
Fixed in 3b884901a1d6c8141e6e3781a30b364e94d170d4
