### ISSUE TITLE
Replacing a texture that has another one with the same name goes back to the first texture after it has been replaced

### ISSUE THREAD

**Issue by bor-real** [PhoenixARC/-PCK-Studio#36]
[screen-recorder-sun-jun-23-2024-14-34-16.webm](https://github.com/PhoenixARC/-PCK-Studio/assets/90580455/5dbd7c3f-b173-4af8-a2d3-e21947606e7e)

**Comment by MattN-L** [comment]
This was a bug that I forgot to fix when we were still in beta lol

**Comment by NessieHax** [comment]
Fixed in d620759
