### ISSUE TITLE
request: pack images?

### ISSUE THREAD

**Issue by lynxsain** [PhoenixARC/-PCK-Studio#39]
![image](https://github.com/user-attachments/assets/163b7877-5b67-4b5b-8c1a-8dea00fc8bc1)
Basically the image that appears above the list of skin packs. I would like the ability to add custom pack preview images. If this feature is already available, I'd appreciate guidance on how to use it, as I'm unsure. (I'm fairly new to modding console minecraft).

**Comment by mattnl42** [comment]
This WAS a feature in development versions of 7.0, but we stripped it simply on the premise that it involves ARC files, and not PCK.

**Comment by MattN-L** [comment]
This WAS a feature in development versions of 7.0, but we stripped it simply on the premise that it involves ARC files, and not PCK.
