### ISSUE TITLE
Maximum Skin Limit Per pack on Wii U?

### ISSUE THREAD

**Issue by playerjmr** [PhoenixARC/-PCK-Studio#41]
Hi, I tried implementing 16 custom skins into a single pack, only to have it crash (real hardware). Is there a hard limit for custom packs on Wii U? or is this a bug with the program? Really just looking for context here since theres hardly any information online regarding this subject. It seems like there are legitimate DLC packs that have way more than 16 skins so im inclined to believe that this is an issue with pck studio.

Then again, I could just be having a skill issue lol.

**Comment by MattN-L** [comment]
Hi! There's no hard skin limit. If you're trying to ADD a new pack on Wii U via FTP, the game will crash. For whatever reason, FTP cannot create valid new directories on Wii U. If you want to add a pack to your Wii U pack with not much setup, i recommend SDCaffiine's mod system to auto load your packs upon loading the game.

**Comment by playerjmr** [comment]
> Hi! There's no hard skin limit. If you're trying to ADD a new pack on Wii U via FTP, the game will crash. For whatever reason, FTP cannot create valid new directories on Wii U. If you want to add a pack to your Wii U with not much setup, i recommend SDCaffiine's mod system to auto load your packs upon loading the game.

Well, it seems like that’s not the case, since it actually worked if I just split the skin pack into two.

Also, SDcafiine was the first thing I tried, and i guess it doesn’t recognize the folder cause the menu didn't pop up at all when launching the game. I should also point out this is Aroma CFW.

**Comment by playerjmr** [comment]
Issue solved over discord: Skin in sub pck was causing the game to crash, full conversation here: https://discord.com/channels/806988877687423027/1144579618230239272/1298515187888029757
