### ISSUE TITLE
Pck files showing empty

### ISSUE THREAD

**Issue by Yekul10** [PhoenixARC/-PCK-Studio#9]
I've tried several versions of PCK Studio and several different pck files, but every time I try and open one, it shows that it's empty:
![PCK_Studio_screenshot](https://user-images.githubusercontent.com/29359831/188994868-c1d514d9-511f-4dcd-8662-6649926df32e.png)

When I run it through FILExt, it shows that it does have content:
![FILExt screenshot](https://user-images.githubusercontent.com/29359831/188995241-fa0b4e76-8905-44ef-b546-bc85b1241474.png)

**Comment by NessieHax** [comment]
this might be a render issue you can try building from source or wait a little till a public 7.0 beta build is available

**Comment by MattN-L** [comment]
This bug should be fixed now in the 7.0 BETA Release
